name: Publish Node.js package

on:
  push:
    branches: 
      - main

permissions:
  contents: write
  packages: write

concurrency:
  group: publish-node-package
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: '@statens-pensjonskasse'
      - run: npm ci
      - name: Get version to use
        id: get_version
        run: |
            echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: npm publish --tag "$VERSION"
