name: Build Node.js Library

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: needs.release-and-publish-mvn.outputs.published == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm ci && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
